// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schendel_Final
{
    public partial class Assignment
    {
        public int AssignmentId { get; set; }
        public int? CourseId { get; set; }
        public DateTime? DueDate { get; set; }
        public string AssignmentDetails { get; set; }
    }
}