// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schendel_Final
{
    public partial class Instructor
    {
        public int InstructorId { get; set; }
        public string InstFirstName { get; set; }
        public string InstLastName { get; set; }
        public string InstEmail { get; set; }
        public string InstPassword { get; set; }
    }
}