// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schendel_Final
{
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string StudEmail { get; set; }
        public string StudPassword { get; set; }
    }
}