// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Schendel_Final
{
    public partial class Submission
    {
        public int SubmissionId { get; set; }
        public int StudentId { get; set; }
        public int AssignmentId { get; set; }
        public string Submission1 { get; set; }
        public DateTime? SubmissionDate { get; set; }
    }
}